[package]
name = "echo"
version = "0.1.0"
authors = ["Cameron Dart <cdart2@illinois.edu>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }

[[bin]]
name = "tcp"
path = "src/tcp.rs"

[[bin]]
name = "udp"
path = "src/udp.rs"
