[package]
name = "echo"
version = "0.1.0"
authors = ["Cameron Dart <cdart2@illinois.edu>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }

[[example]]
name = "server"
path = "src/server.rs"

[[example]]
name = "client"
path = "src/client.rs"